### ISSUE TITLE
[Feature] Configure application system's user list UI to support groups

### ISSUE THREAD

**Issue by DedsecKnight** [hackutd/hackutd-24-site#120]
# Overview

Current UI does not take the newly-implemented group system into consideration and only displays each application by itself. Hence, we need to display apps in a way such that each row in application list corresponds to a group. 

# Task list
- [ ] Modify the backend to return users in groups instead. 
    - [ ] Modify the `/api/users` endpoint to return the result of [this function](https://github.com/hackutd/hackutd-24-site/blob/develop/pages/api/users/index.ts#L65). 
    - [ ] Make sure that names are converted to `Anonymous` if user is not **super admin**.
- [ ] Refactor `AllUsersAdminView` so that each row of the table corresponds to the group of user. 
    - [ ] Update props interface to reflect the fact that component expects list of groups instead of list of users. 
    - [ ] Update functions such as `onUserClick` and `onAcceptReject` to support group instead of single user. 
- [ ] Refactor `UserList` component to reflect the fact that component expects a list of groups instead of list of users. 
    - [ ] For information such as major, university, and study level, if group has more than 1 users, then concatenate information with comma (i.e: "freshman, freshman, sophomore, junio")
