### ISSUE TITLE
[Feature] Configure application system's single-user UI to support group. 

### ISSUE THREAD

**Issue by DedsecKnight** [hackutd/hackutd-24-site#121]
# Overview

Current UI does not take the newly-implemented group system into consideration and only displays each application by itself. Hence, we need to add support for groups in single-user UI.

# Task List
- [ ] Update interface of `UserAdminView` to reflect the fact that component expects group instead of a single user. 
    - [ ] Update `users` to expected a list of list of users. 
    - [ ] Update `currentUserId` to expect id of group (easiest will be concatenating id of all users in the group with "-", i.e "<userid1>-<userid2>-<userid3>-<userid4>", but feel free to try something else that works better). 
    - [ ] Update `onAcceptReject` to support group acceptance / rejection. 
    - [ ] Update `onUpdateRole` so that role is updated for **a single user** only.
