### ISSUE TITLE
[Feature] Add support for new application rating system. 

### ISSUE THREAD

**Issue by DedsecKnight** [hackutd/hackutd-24-site#122]
# Overview

Currently, application system only supports accept or reject verdict. We want to add support for maybe verdict.  

# Task List
- [ ] Add a new button for `MAYBE` in `UserAdminView`. 
    - [ ] When clicking `MAYBE` button, user will be prompted to choose between `MAYBE YES` and `MAYBE NO`. 
- [ ] Upon choosing a verdict, frontend will create a list of verdicts for all users within the group and send the list to backend at `/api/scoring` endpoint.
