### ISSUE TITLE
[Feature] Improve hidden div

### ISSUE THREAD

**Issue by DedsecKnight** [hackutd/hackutd-24-site#73]
# Overview

Improve the UI of hidden div according to Marketing's request. 

# Task List
- [x] Bigger doggo
- [x] Fix schedule div
- [x] Duck goes across the page
- [x] Parallax animation of waves
- [x] More clouds on hidden div
- [x] More fishy movements
- [ ] Fishies follow your mouse
- [x] Schedule edge radius less

**Comment by vvyn** [comment]
Questions
- better resolution on doggo on boat
