### ISSUE TITLE
[Feature] Improve Navbar

### ISSUE THREAD

**Issue by DedsecKnight** [hackutd/hackutd-24-site#74]
# Overview

Improve the UI of navbar according to Marketing's request. 

# Task List
- [ ] Add hover effect on text and button
- [ ] Add bg blur
- [ ] Less padding
- [ ] Resource section
- [ ] MagicUI
- [ ] Aceternity UI Navbar Animation

# Supplemental Information
- [Aceternity Floating Dock](https://ui.aceternity.com/components/floating-dock)
- [Aceternity Floating Navbar](https://ui.aceternity.com/components/floating-navbar)
- [MagicUI](https://magicui.design/docs/components/dock)
