### ISSUE TITLE
[Feature] Fix footer

### ISSUE THREAD

**Issue by DedsecKnight** [hackutd/hackutd-24-site#77]
# Overview

Apply fix into footer according to Marketing's request. 

# Task List
- [x] Change the "Follow our Newsletter" email text to be visible, darker color. 
- [x] Add social media icons: insta, linkedin, email
- [x] Add copyright info (refer to figma design)

# Supplemental Information
- [Figma Design](https://www.figma.com/design/BSOPrukZwW5erkftrHb30y/HackPortal?node-id=5383-374&t=KYodf3iKkYSwcNuJ-0)
- [HackUTD Instagram URL](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.instagram.com/hackutd/%3Fhl%3Den&ved=2ahUKEwi-k-bnlsCIAxXdLtAFHXidKfQQFnoECB4QAQ&usg=AOvVaw0NkD6myV_i0nzqoQsaCHu0)
- [HackUTD LinkedIn URL](https://www.linkedin.com/company/hackutd)
- HackUTD email: hello@hackutd.co
