### ISSUE TITLE
[Feature] Endpoint to fetch application for review

### ISSUE THREAD

**Issue by DedsecKnight** [hackutd/hackutd-24-site#80]
# Overview

Implement an API endpoint that allows organizers to fetch applications that they need to review. 

# Task List
- [x] Solution should be able to fetch applications that organizers are assigned according to #79 
- [x] Solution should be able to fetch applications within common pool. 
- [x] Organizers should be able to view notes and scores provided to applications that are in common pool and **are not** in the batch assigned to them by #79. 
- [x] For apps that are in common pool, scores and notes are only viewable if organizers are not "assigned" the app according to #79. 
- [x] Reviewer info should be anonymized. 
- [x] Application info should be anonymized. 

# Supplemental Information
- An application belongs to the common pool if either of the following conditions hold: 
    - App receives 1 Strong Yes and 1 Strong No vote. 
    - App receives at least 1 Maybe vote.
