### ISSUE TITLE
[Feature] Application scoring submission mechanism

### ISSUE THREAD

**Issue by DedsecKnight** [hackutd/hackutd-24-site#81]
# Overview
Implement API endpoint for organizers to submit their scoring of an application. 

# Task List
- [x] Should be able to handle team scoring. 
- [x] Should allow organizers to add notes into application. 
- [x] Application should be moved to common pool if they receive 1 Strong Yes and 1 Strong No. 
- [x] Application should be moved to common pool if they receive at least 1 Maybe. 

# Supplemental Information
- In HackUTD X, data related to application scoring is structured as follow: 
```json
{
    "hackerId": "some_id",
    "organizerId": "some_id",
    "verdict": "accepted",
}
```
