### ISSUE TITLE
[Feature] Update website assets

### ISSUE THREAD

**Issue by DedsecKnight** [hackutd/hackutd-24-site#94]
# Overview

Need to update new assets on the website. 

# Task List
- [x] Separate lilypads from hero. 
    - [x] Assets for both lilypads and new hero background will be provided. 
- [x] Replace cloud asset for countdown cloud. 
- [ ] Replace wave asset at the bottom of the page. 
- [ ] Replace wave asset between statistics section and "What is HackUTD" section
- [x] Replace mascot and duck in hero section. 
- [x] Replace koi fish in "What is HackUTD" section. 
- [x] Replace frog on hot air balloon asset. 
- [x] Replace duck row asset. 
- [x] Replace corgi asset.

# Supplemental Information
- [Google Drive folder containing new assets](https://drive.google.com/drive/u/1/folders/15QrVv8dtcLRANzu76QJP4ulkFSJQG_O4)
